# Generated by Django 3.0.2 on 2020-02-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_suggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestion_body',
            new_name='suggestion_text',
        ),
    ]
