# Generated by Django 3.0.2 on 2020-02-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0003_auto_20200202_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
