# Generated by Django 3.0.2 on 2020-02-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0004_delete_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(max_length=200)),
                ('suggestion_text', models.TextField(max_length=200)),
            ],
        ),
    ]
