# Generated by Django 3.0.2 on 2020-02-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0009_suggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
