# Generated by Django 3.0.2 on 2020-07-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0012_remove_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='player_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
