# Generated by Django 3.0.2 on 2020-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0013_auto_20200709_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='coach_name',
            new_name='coach_lname',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='player_name',
            new_name='player_lname',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='position',
            new_name='player_position',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='city',
            new_name='team_city',
        ),
        migrations.RemoveField(
            model_name='search',
            name='player_age',
        ),
        migrations.AddField(
            model_name='search',
            name='player_birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
