# Generated by Django 3.0.2 on 2020-07-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0014_auto_20200709_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlight',
            old_name='id',
            new_name='highlight_id',
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlight_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
