# Generated by Django 3.0.2 on 2020-07-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0015_auto_20200709_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='game_date',
        ),
        migrations.RemoveField(
            model_name='search',
            name='player_birthdate',
        ),
    ]
